query POPULARITY($name: String!){
  	rateLimit{
      cost
      remaining
    }
    repositoryOwner(login: $name) {
        ... on User {
            followers(first: 0){
            	totalCount
          	}
          	repositories(first: 50, orderBy: {field: STARGAZERS, direction: DESC}){
            	edges{
                node{
                  nameWithOwner
                  stargazers(first: 0){
                    totalCount
                  }
                  forks(first: 0){
                    totalCount
                  }
                }
              }
          	}          	
          }
       }
    }