query($name: String!){
    repositoryOwner(login: $name) {
        login
        ... on User {
            email
            bio
            name
          	avatarUrl
            websiteUrl
            followers(first: 0) {
            totalCount
            }
            following(first: 0){
            totalCount
            }
          	repositories(first: 0){
            	totalCount
          	}
          	organizations(first: 0){
            	totalCount
          	}
        }
    }
}